name: Deploy to Lambda

on:
  push:

jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v0.0.1
        with:
          args: |
            --access-key ${{ secrets.AWS_ACCESS_KEY_ID }}
            --secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            --region us-east-1
            --function-name LeshegoApiFunction
            --zip-file bundle.zip